### ISSUE TITLE
Missing NPM package: `autobind-decorator`

### ISSUE THREAD

**Issue by retzion** [brycedorn/react-intense#12]
```
./node_modules/react-intense/dist/ReactIntense.js
Module not found: Can't resolve 'autobind-decorator' in '/Users/reuven/Projects/STL/stl-pwa/node_modules/react-intense/dist'
```

I've uninstalled and reinstalled `react-intense` a few times and it didn't help.
Here are my dependencies:
```
"dependencies": {
    "@fortawesome/fontawesome-svg-core": "1.2.17",
    "@fortawesome/free-solid-svg-icons": "5.8.1",
    "@fortawesome/react-fontawesome": "0.1.4",
    "@typeform/embed": "0.5.12",
    "animate.css": "3.7.0",
    "node-fetch": "2.3.0",
    "react": "16.8.5",
    "react-animate-on-scroll": "2.1.5",
    "react-device-detect": "1.6.2",
    "react-dom": "16.8.5",
    "react-ga": "2.5.7",
    "react-google-login": "4.0.1",
    "react-intense": "^0.1.6",
    "react-popup": "0.9.3",
    "react-router-dom": "4.3.1",
    "react-scripts": "2.1.8",
    "react-stripe-checkout": "2.6.3",
    "semantic-ui-css": "2.4.1",
    "semantic-ui-react": "0.84.0",
    "sohotokenlabs-api": "1.0.20",
    "stripe": "6.28.0",
    "uuid": "3.3.2"
  }
```

**Comment by retzion** [comment]
Adding `autobind-decorator` as a dependency provides a way around failure due to the package not being found in the `dist` dir. Not ideal, but I can change things when this is resolved.

**Comment by tommyboylab** [comment]
I'm also encountering this issue, would appreciate this being resolved.

**Comment by shanmugarajbe** [comment]
Even I am facing this issue. Any solution?

**Comment by baseRed** [comment]
me too!

**Comment by brycedorn** [comment]
hi @retzion, sorry for the (super) late response on this one. I didn't get notifications for issues, so didn't see until now. but thank you for pointing this out!

I switched the project to use npm (which I use instead of yarn now) and re-added the dependency which should resolve the issue.

**Comment by iiw** [comment]
This still does exist.

**Comment by brycedorn** [comment]
hey @iiw, sorry about that. just removed the package entirely, should be (actually) resolved now 😄
