### ISSUE TITLE
Scrolling disabled after dismissing enlarged image

### ISSUE THREAD

**Issue by retzion** [brycedorn/react-intense#13]
Across multiple browsers, I have found that after dismissing an enlarged image I am unable to scroll on the page anymore. There must be an event to release the locked scrolling that is not getting hit. I see nothing in the console.

**Comment by retzion** [comment]
Looks like the body `overflow` style attribute is not getting removed:
`<body style="overflow: hidden;">`

**Comment by retzion** [comment]
This workaround worked for me:
```
componentDidMount() {
    document.addEventListener('mousedown', userEvent => {
        const parentClass = userEvent.path[0].parentNode.className
        if (parentClass === 'ri-container') document.body.style.overflow = null
    })
}
```

**Comment by brycedorn** [comment]
hi @retzion, thanks for reporting this! I fixed this by adding a default `overflow` value here: 

https://github.com/brycedorn/react-intense/pull/19/commits/8a3a508bf7fb6d2d47e1584b0dbdfbacfe76954e#diff-fc54d6f3ba01e57d5a2b04c10950c39bR103
