### ISSUE TITLE
Usage with NextJS not possible

### ISSUE THREAD

**Issue by pojntfx** [brycedorn/react-intense#20]
Currently, this library `require`-s the CSS; this fails when used with NextJS:

```bash
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/react-intense/dist/ReactIntense.js
```

A possible fix could be to prefer manually importing the CSS.

**Comment by brycedorn** [comment]
thanks for pointing this out @pojntfx - I haven't tested with that framework. you're right - this import should be up to the user, not hardcoded:

https://github.com/brycedorn/react-intense/blob/4d8baceb2223464c899fd1ae0e5a594969787775/lib/ReactIntense.js#L16

**Comment by pojntfx** [comment]
Thanks for your response! It would indeed be great to be able to import the CSS manually. Next have fixed the bug of not being able to import CSS nowadays however: https://nextjs.org/blog/next-10#importing-css-from-third-party-react-components so it should no longer affect this project.

**Comment by brycedorn** [comment]
closing if this is no longer issue - can update if needed.

**Comment by prullansky** [comment]
Hi! I seem to have the same problem, even if as @pojntfx noted, Next has solved the issue.

Could any of you guide me on how to solve it? I have tried importing the css file on _app.js, as well as in the component where I would like to use it and no luck, I keep having the 'Global CSS cannot be imported from within node_modules.' error message.

Thanks a lot :_)

**Comment by mlclmtan** [comment]
Same problem with @prullansky , it would be helpful if someone could guide using react-intense in Nextjs :)
