### ISSUE TITLE
0.1.11 version doesn't work with React 18.2.0

### ISSUE THREAD

**Issue by ameer-clara** [brycedorn/react-intense#30]
When importing
```javascript
import ReactIntense from "react-intense";
```
throws
```bash
Module not found: Error: Can't resolve 'react-intense'
```

**Comment by brycedorn** [comment]
hi @ameer-clara, thanks for reporting this! should be resolved with #31, let me know if you're still having issues.

**Comment by ameer-clara** [comment]
Thanks for looking into this, I pulled the latest(0.1.12) and get the same error, reverting to 0.1.9 solves the problem.
<img width="953" alt="Screen Shot 2022-10-01 at 6 14 01 PM" src="https://user-images.githubusercontent.com/60880191/193430339-62cd5597-6db7-4aba-a407-ccc0c748b24a.png">

**Comment by brycedorn** [comment]
hi! found the issue - was missing a `main` entry in package.json for most recent version. fixed now, here's a [codesandbox](https://codesandbox.io/s/inspiring-turing-0p2984?file=/src/App.tsx) example.

it doesn't have proper typescript integration so you'll still get that error but it works :)

**Comment by ameer-clara** [comment]
Thanks, it works now.
