### ISSUE TITLE
Cannot get it run in my app or with your repo.

### ISSUE THREAD

**Issue by MainzerKaiser** [brycedorn/react-intense#35]
When I test your orginal git repo I'll get the error message:

> npm start error: no native build was found for platform=linux arch=x64 runtime=node abi=108 uv=1 libc=glibc node=18.0.0

When I test it in my application either with installed react-intense or local copy in lib folder (like in your repo) there are no pitures shown and there is no error message in the console of my edge browsers.

Am I missing any requirements?

**Comment by brycedorn** [comment]
Hi @MainzerKaiser do you have node installed/which version?

**Comment by MainzerKaiser** [comment]
Hi Bryce, thanks for getting back, but this is so long ago. I cannot reproduce the problem anymore. I ended up using another library.
